source("./src/utils/utils.R")
source("./src/setup/setup.R")
source("./src/filter/filter.R")
source("./src/hypervolume/data_acquisition/data_acquisition.R")
source("./src/hypervolume/data_analysis/data_analysis.R")
source("./src/hypervolume/data_processing/data_processing.R")
source("./src/hypervolume/hv_analysis/hv_analysis.R")
source("./src/hypervolume/parallel.R")
source("./src/hypervolume/node.R")

source("./src/main.R")
